GET http://127.0.0.1:6666/user-api/users
###

POST http://127.0.0.1:6666/user-api/users 
Content-Type: application/json

{
    "username":"divya",
    "email":"div@gmail.cart",
    "password":2222,
    "cart":[]
}